name: ci

on:
  push:
    branches:
      - "develop"
    tags-ignore:
      - "*"
  pull_request: ~
  workflow_dispatch: ~

jobs:

  # Calls a reusable CI workflow to build & test current repository.
  #   It will pull in all needed dependencies and produce a code coverage report on success.
  #   In case the job fails, a message will be posted to a Microsoft Teams channel.
  ci:
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v1
    with:
      codecov_upload: false
      notify_teams: false
      
      build_package_inputs: |
        dependencies: |
          ecmwf/ecbuild
          ecmwf/eckit
          MathisRosenhauer/libaec@master
        dependency_branch: develop
        cmake_options: -DENABLE_MEMFS=ON -DBUILD_SHARED_LIBS=OFF -DENABLE_FORTRAN=OFF
